name: Publish Housekeeping Image

on:
  pull_request:
    paths:
      - ".github/workflows/publish_housekeeping.yml"
      - "docker/Dockerfile.housekeeping"

jobs:
  build-for-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    name: Publish Housekeeping
    steps:
      - name: Tag as ci-image-cache
        run: |
          echo "TAG=ci-image-cache" >> "$GITHUB_ENV"

      - name: Tag as Latest
        if: ${{ github.repository_owner == 'cyclus' }}
        run: |
          echo "TAG=latest" >> "$GITHUB_ENV"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Cyclus
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Housekeeping
        uses: docker/build-push-action@v5
        with:
          cache-from: type=registry,ref=ghcr.io/cyclus/cyclus-ci-ubuntu-22.04-housekeeping:ci-layer-cache
          file: docker/Dockerfile.housekeeping
          push: true
          tags: ghcr.io/cyclus/cyclus-ci-ubuntu-22.04-housekeeping:${{ env.TAG }}
          build-args: |
            UBUNTU_VERSION=22.04
            TAG=${{ env.TAG }}
            OWNER=${{ github.repository_owner }}
